# Generated by Django 4.2.16 on 2026-06-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_statement_file_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'bank_pass_user_idx') THEN
                    ALTER INDEX bank_pass_user_idx RENAME TO bank_passwo_user_id_6f2b16_idx;
                ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'bank_passwo_user_id_6f2b16_idx') THEN
                    CREATE INDEX bank_passwo_user_id_6f2b16_idx ON api_bankpassword (user_id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'bank_passwo_user_id_6f2b16_idx') THEN
                    ALTER INDEX bank_passwo_user_id_6f2b16_idx RENAME TO bank_pass_user_idx;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_user_id_idx') THEN
                    ALTER INDEX statements_user_id_idx RENAME TO statements_user_id_2b171c_idx;
                ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_user_id_2b171c_idx') THEN
                    CREATE INDEX statements_user_id_2b171c_idx ON api_statement (user_id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_user_id_2b171c_idx') THEN
                    ALTER INDEX statements_user_id_2b171c_idx RENAME TO statements_user_id_idx;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_card_id_idx') THEN
                    ALTER INDEX statements_card_id_idx RENAME TO statements_card_id_85c183_idx;
                ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_card_id_85c183_idx') THEN
                    CREATE INDEX statements_card_id_85c183_idx ON api_statement (card_id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_card_id_85c183_idx') THEN
                    ALTER INDEX statements_card_id_85c183_idx RENAME TO statements_card_id_idx;
                END IF;
            END $$;
            """,
        ),
    ]
