# Generated by Django 4.2.16 on 2026-06-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_statement_file_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankpassword',
            new_name='bank_passwo_user_id_6f2b16_idx',
            old_name='bank_pass_user_idx',
        ),
        migrations.RenameIndex(
            model_name='statement',
            new_name='statements_user_id_2b171c_idx',
            old_name='statements_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='statement',
            new_name='statements_card_id_85c183_idx',
            old_name='statements_card_id_idx',
        ),
    ]
