# Generated by Django 4.2.16 on 2026-06-29 05:44
# Fixed: use SeparateDatabaseAndState so Django state is updated while DB
# operation is safe for production databases that may be missing the old index.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_statement_file_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'bank_pass_user_idx') THEN
                            ALTER INDEX bank_pass_user_idx RENAME TO bank_passwo_user_id_6f2b16_idx;
                        ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'bank_passwo_user_id_6f2b16_idx') THEN
                            CREATE INDEX bank_passwo_user_id_6f2b16_idx ON bank_passwords (user_id);
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_user_id_idx') THEN
                            ALTER INDEX statements_user_id_idx RENAME TO statements_user_id_2b171c_idx;
                        ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_user_id_2b171c_idx') THEN
                            CREATE INDEX statements_user_id_2b171c_idx ON statements (user_id);
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_card_id_idx') THEN
                            ALTER INDEX statements_card_id_idx RENAME TO statements_card_id_85c183_idx;
                        ELSIF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'statements_card_id_85c183_idx') THEN
                            CREATE INDEX statements_card_id_85c183_idx ON statements (card_id);
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='bankpassword',
                    new_name='bank_passwo_user_id_6f2b16_idx',
                    old_name='bank_pass_user_idx',
                ),
                migrations.RenameIndex(
                    model_name='statement',
                    new_name='statements_user_id_2b171c_idx',
                    old_name='statements_user_id_idx',
                ),
                migrations.RenameIndex(
                    model_name='statement',
                    new_name='statements_card_id_85c183_idx',
                    old_name='statements_card_id_idx',
                ),
            ],
        ),
    ]
