# Generated by Django 4.2.16 on 2026-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_bank_pass_user_idx_bank_passwo_user_id_6f2b16_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund'), ('transfer', 'Transfer'), ('deposit', 'Deposit'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund (Merchant)'), ('REVERSAL', 'Reversal / Void'), ('CARD_PAYMENT', 'Card Payment'), ('CASH_WITHDRAWAL', 'Cash Withdrawal (ATM)'), ('CASH_ADVANCE', 'Cash Advance'), ('TRANSFER', 'Transfer'), ('WALLET_TOPUP', 'Wallet Top-Up'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('INSTALLMENT_PRINCIPAL', 'Installment / BNPL'), ('BANK_FEE', 'Bank Fee'), ('FINANCE_CHARGE', 'Finance Charge / Interest'), ('FOREIGN_EXCHANGE_FEE', 'Foreign Exchange Fee'), ('CASHBACK', 'Cashback'), ('REWARD_CREDIT', 'Reward / Miles Credit'), ('CHARGEBACK', 'Chargeback'), ('ADJUSTMENT', 'Adjustment'), ('PREAUTH_HOLD', 'Pre-Auth Hold'), ('PREAUTH_RELEASE', 'Pre-Auth Release'), ('QUASI_CASH', 'Quasi-Cash'), ('UNKNOWN', 'Unknown')], max_length=50),
        ),
    ]
