# Generated by Django 4.2.16 on 2026-06-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_new_transaction_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('company', 'Company'), ('personal', 'Personal'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchant_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(choices=[('company', 'Company'), ('personal', 'Personal'), ('unclassified', 'Unclassified')], default='unclassified', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.merchantgroup'),
        ),
        migrations.CreateModel(
            name='MerchantRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('starts_with', 'Starts With')], default='contains', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.merchantgroup')),
            ],
            options={
                'db_table': 'merchant_rules',
                'indexes': [models.Index(fields=['merchant_name'], name='merchant_rule_name_idx')],
                'unique_together': {('group', 'merchant_name')},
            },
        ),
        migrations.AddIndex(
            model_name='merchantgroup',
            index=models.Index(fields=['user_id'], name='merchant_group_user_idx'),
        ),
    ]
